version: '3.2'

services:

#================================================================================================
# TERRAFORM
#================================================================================================
  terraform:
    image: bhuisgen/alpine-terraform
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/data
