ARG ALPINE_VERSION=3.6
ARG PHPMYADMIN_VERSION=4.8.0
FROM alpine:${ALPINE_VERSION}

# ================================================================================================
#  Inspiration: Docker Framework (https://github.com/zeroc0d3/docker-framework)
#               ZeroC0D3 Engineer <zeroc0d3.0912@gmail.com>
# ================================================================================================
#  Core Contributors:
#  - Mahmoud Zalt @mahmoudz
#  - Bo-Yi Wu @appleboy
#  - Philippe Trépanier @philtrep
#  - Mike Erickson @mikeerickson
#  - Dwi Fahni Denni @zeroc0d3
#  - Thor Erik @thorerik
#  - Winfried van Loon @winfried-van-loon
#  - TJ Miller @sixlive
#  - Yu-Lung Shao (Allen) @bestlong
#  - Milan Urukalo @urukalo
#  - Vince Chu @vwchu
#  - Huadong Zuo @zuohuadong
# ================================================================================================

MAINTAINER "Laradock Team <mahmoud@zalt.me>"

ENV PHPMYADMIN_VERSION=${PHPMYADMIN_VERSION}

ENV PMA_ARBITRARY="1" \
    PMA_HOST="localhost" \
    PMA_PORT="3306" \
    PMA_USER="laradock" \
    PMA_PASSWORD="password"

RUN apk add --update curl tar zip unzip && \
    mkdir -p /var/www && \
    mkdir -p /sessions && \
    # curl -sSL https://files.phpmyadmin.net/phpMyAdmin/${PHPMYADMIN_VERSION}/phpMyAdmin-${PHPMYADMIN_VERSION}-english.tar.gz | \
    #    tar -xzo -C /var/www --strip-components 1 && \
    curl -o /var/www -sSL https://files.phpmyadmin.net/phpMyAdmin/${PHPMYADMIN_VERSION}/phpMyAdmin-${PHPMYADMIN_VERSION}-all-languages.zip | \
       unzip /var/www/phpMyAdmin-${PHPMYADMIN_VERSION}-all-languages.zip && \
    apk del curl tar && \
    rm -rf /var/cache/apk/*

# We expose PhpMyAdmin on port 80 (PhpMyAdmin's default)
EXPOSE 80

ENTRYPOINT ["/bin/sh"]
CMD []
VOLUME ["/var/www", "/sessions"]

