version: '3.2'

services:

#================================================================================================
# NGINX
#================================================================================================
  nginx:
    restart: always
    build:
      context: .
    links:
      - workspace
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ${CONFIG_NGINX}:/etc/nginx/nginx.conf                  # nginx config path
      - ${CONFIG_NGINX_PHPFPM}:/etc/nginx/conf.d/default.conf   # phpfpm config path
      - ${LOG_NGINX}:/var/log/nginx                             # log nginx
      - ${WORKSPACE}:/var/www                                   # volume for data
    environment:
      - NGINX_VERSION=${NGINX_VERSION}
